name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get update && sudo apt -y install libxrandr-dev libxinerama-dev libxcursor-dev libx11-dev g++-8 libmpv-dev libxi-dev
    - name: get submodules
      run: git submodule update --init
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: test LogReader
      run: make test
