name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Add PPA
      run: sudo add-apt-repository ppa:mc3man/bionic-media -y
    - name: install dependencies
      run: sudo apt-get update && sudo apt -y install libxrandr-dev libxinerama-dev libxcursor-dev libx11-dev g++-8 libmpv-dev libxi-dev freeglut3-dev libmpv-dev
    - name: get submodules
      run: git submodule update --init
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: test LogReader
      run: make test
