name: Linux

on: [push]

jobs:
  build_ubuntu_20.04:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Add PPA
      run: sudo add-apt-repository ppa:mc3man/bionic-media -y
    - name: install dependencies
      run: sudo apt-get update && sudo apt -y install libxrandr-dev libxinerama-dev libxcursor-dev libx11-dev libxi-dev freeglut3-dev
    - name: get submodules
      run: git submodule update --init
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: test LogReader
      run: make test
