name: Windows

on: [push]

jobs:
  build_windows_2016:

    runs-on: windows-2016
    
    steps:
    - uses: actions/checkout@v1
    - name: get submodules
      run: git submodule update --init
    - name: cmake
      run: cmake .
    - name: build
      run: cmake --build . --config Release
    - name: test LogReader
      run: ctest -C "Release"
    - name: upload artifact
     uses: actions/upload-artifact@v1
     with:
       name: OpenRaceRender
       path: Release\OpenRaceRender.exe
